// Copied from project-level firebase_options.dart generated by FlutterFire CLI.
// Provides a single source so both apps can import `package:shared/firebase_options.dart`.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'please re-run the FlutterFire CLI targeting web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'please re-run the FlutterFire CLI targeting macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'please re-run the FlutterFire CLI targeting windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'please re-run the FlutterFire CLI targeting linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfgnDrp7SV4vSMYh8i5XQcaPSkN-4mYh4',
    appId: '1:876178419860:android:6be55cbda5b50fd0358481',
    messagingSenderId: '876178419860',
    projectId: 'wtf-gym-80f24',
    storageBucket: 'wtf-gym-80f24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrTyZXuZev-K98BKaVJNOgCcFS3H_jMgM',
    appId: '1:876178419860:ios:b4e7116217fb3849358481',
    messagingSenderId: '876178419860',
    projectId: 'wtf-gym-80f24',
    storageBucket: 'wtf-gym-80f24.firebasestorage.app',
    iosBundleId: 'com.example.wtfFlutterTest',
  );
}
